In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import pickle
from tensorflow.keras.models import load_model
from sklearn.compose import ColumnTransformer

In [46]:
model = load_model('model.h5')

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('one_hot_encoder_geography.pkl', 'rb') as file:
    one_hot_encoder_georgaphy = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [47]:
# Example of input Data

input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male', 
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

input_df = pd.DataFrame([input_data])

In [48]:
geo_encoded = one_hot_encoder_georgaphy.transform(
    input_df[['Geography']]
)

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=one_hot_encoder_georgaphy.get_feature_names_out(['Geography'])
)

geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [49]:
# Encode my Categorical Variable

input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])

In [50]:
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [51]:
# Concatenation of One Hot Encoded Data

input_df = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [52]:
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [53]:
# Prediction
prediction = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

In [57]:
prediction_proba = prediction[0][0]

In [58]:
if prediction_proba > 0.5:
    print('The Customer is Likely to Churn')
else:
    print('The Customer is not Likely to Churn')

The Customer is not Likely to Churn